import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider } from "@/lib/thirdweb";
import { AuthProvider } from "@/contexts/AuthContext";
import BottomNav from "@/components/BottomNav";
import Header from "@/components/Header";
import { Box } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ThirdwebProvider>
            <Header />
            <Box
              sx={{
                minHeight: "100vh",
                bgcolor: "white",
                pt: "76px", // 👈 เว้นระยะด้านบนเท่ากับ Header
                pb: "40px", // 👈 (ถ้ามี BottomNav fixed ด้วย)
              }}
            >
              {children}
            </Box>
            <BottomNav />
          </ThirdwebProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
